# Array Elemanlari Arasinda 4 Islem

In [2]:
import numpy as np

In [14]:
arr1 = np.array([10, 20, 40, 80])
arr2 = np.array([3, 9, 17, 4])

In [15]:
arr1

array([10, 20, 40, 80])

In [16]:
arr2

array([ 3,  9, 17,  4])

In [17]:
arr1 + arr2 # arraylerin elemanlari arasinda toplama islemi yapar

array([13, 29, 57, 84])

In [18]:
arr1.__add__(arr2) # ustteki ile ayni islemi yapar

array([13, 29, 57, 84])

In [19]:
arr1 - arr2 # cikarma islemi

array([ 7, 11, 23, 76])

In [20]:
arr1.__sub__ (arr2) # ustteki ile ayni islemi yapar

array([ 7, 11, 23, 76])

In [21]:
arr1 * arr2 # carpma islemi

array([ 30, 180, 680, 320])

In [ ]:
arr1 ** arr2 # us alma islemi

array([               1000,        512000000000, 8514055095543922688,
                  40960000])

In [23]:
arr1 / arr2 # bolme islemi

array([ 3.33333333,  2.22222222,  2.35294118, 20.        ])

In [ ]:
arr1 // arr2 # floor = tam sayi bolme islemi

array([ 3,  2,  2, 20])

# Arrayin icindeki elemanlarin toplami/ortalamasi/varyansi/standart sapmasi

In [25]:
arr3 = np.random.randint(0, 24, 12)
arr3

array([11,  0, 12, 23,  7, 19,  8,  5, 20,  9, 15,  5], dtype=int32)

In [28]:
arr3.sum() # sum() bir arrayin icindeki elemanlarin toplamini verir

np.int64(134)

In [29]:
arr3.mean() # mean() bir arrayin icindeki elemanlarin ortalamasini verir

np.float64(11.166666666666666)

In [ ]:
arr3.var() # var() bir arrayin icindeki elemanlarin varyansini verir
# varyans: verilerin ortalamaya olan uzakliklarinin ortalamasi

np.float64(43.97222222222223)

In [ ]:
arr3.std() # std() bir arrayin icindeki elemanlarin standart sapmasini verir
# standart sapma: verilerin ortalamaya olan uzakliklarinin ortalamadan ne kadar saptigini gosterir

np.float64(6.631155421359254)

In [32]:
np.sqrt(arr3) # sqrt() bir arrayin icindeki elemanlarin karekokenini verir

array([3.31662479, 0.        , 3.46410162, 4.79583152, 2.64575131,
       4.35889894, 2.82842712, 2.23606798, 4.47213595, 3.        ,
       3.87298335, 2.23606798])

In [33]:
np.sin(arr3) # sin() bir arrayin icindeki elemanlarin sinus degerlerini verir

array([-0.99999021,  0.        , -0.53657292, -0.8462204 ,  0.6569866 ,
        0.14987721,  0.98935825, -0.95892427,  0.91294525,  0.41211849,
        0.65028784, -0.95892427])

In [34]:
np.cos(arr3) # cos() bir arrayin icindeki elemanlarin cosinus degerlerini verir

array([ 0.0044257 ,  1.        ,  0.84385396, -0.53283302,  0.75390225,
        0.98870462, -0.14550003,  0.28366219,  0.40808206, -0.91113026,
       -0.75968791,  0.28366219])

In [36]:
arr3.max() # max() bir arrayin icindeki en buyuk elemani verir

np.int32(23)

In [37]:
arr3.min() # min() bir arrayin icindeki en kucuk elemani verir

np.int32(0)

# (Concatenate) NumPy Arraylari Birlestirme

In [38]:
arr1

array([10, 20, 40, 80])

In [39]:
arr2

array([ 3,  9, 17,  4])

In [42]:
arr4 = np.concatenate((arr1, arr2)) # concatenate() iki veya daha fazla arrayi birlestirir
# default olarak axis=0 (satir bazinda) birlestirme yapar

In [41]:
arr4

array([10, 20, 40, 80,  3,  9, 17,  4])

In [43]:
arr2d1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2d2 = np.array([[7, 8, 9], [10, 11, 12]])

In [44]:
arr2d3 = np.concatenate((arr2d1, arr2d2), axis = 1) # axis=1 (sutun bazinda) birlestirme yapar

In [45]:
arr2d3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# (Yiginlama) Arrayleri Stackleme

In [48]:
# Concatenate ile farki yeni bir boyut ekler
arr2d4 = np.stack((arr2d1, arr2d2), axis = 0)

In [49]:
arr2d4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#np.vstack((arr2d1, arr2d2)) # vertical stack (dikey yiginlama) yapar
#np.hstack((arr2d1, arr2d2)) # horizontal stack (yatay yiginlama) yapar

# NumPy Arraylerinde Arama

In [ ]:
np.where(arr2d4 == 8) # arr2d4 icindeki 8 sayisinin indeksini verir

(array([1]), array([0]), array([1]))

In [53]:
arr5 = np.random.randint(0, 50, 18)
arr5

array([23, 13,  1,  5, 17,  5,  3, 19, 45, 37, 36, 21,  4, 24, 49, 38,  6,
       38], dtype=int32)

In [ ]:
np.where(arr5 > 25) # arr5 icindeki 25'ten buyuk elemanlarin indekslerini verir

(array([ 8,  9, 10, 14, 15, 17]),)

In [ ]:
np.where(arr5 % 2 != 0) # arr5 icindeki tek sayilarin indekslerini verir

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 14]),)