# NumPy : Numerical Python

In [4]:
import numpy as np

In [ ]:
np.array(53) # 0 boyutlu array

array(53)

In [6]:
np.array([1, 2, 3, 4, 5]) # 1 tane koseli parantez oldugundan 1 boyutlu array olur

array([1, 2, 3, 4, 5])

In [ ]:
np.array([ # 2 tane koseli parantez oldugundan 2 boyutlu array olur
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 3 boyutlu array
print(arr3d[0], "\n") # 3 boyutlu arrayin 0. indexindeki 2 boyutlu arrayi verir
print(arr3d[0][0], "\n") # 3 boyutlu arrayin 0. indexindeki 2 boyutlu arrayin 0. indexindeki 1 boyutlu arrayi verir
print(arr3d[0][0][0], "\n") # 3 boyutlu arrayin 0. indexindeki 2 boyutlu arrayin 0. indexindeki 1 boyutlu arrayin 0. indexindeki elemani verir
print(arr3d.ndim) # arrayin boyut sayisini verir

[[1 2 3]
 [4 5 6]] 

[1 2 3] 

1 

3


In [52]:
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
print(np.arange(1, 11)) # 1'den 11'e kadar (11 dahil degil) sayilarla array olusturur, daha pratik yol
print(np.arange(1, 11, 2)) # 1'den 11'e kadar 2ser 2ser artarak sayilarla array olusturur
print(np.linspace(2, 10, 5)) # 1 ile 10 arasinda esit araliklarla 5 sayi olusturur, 10 dahil
# arange ile linspace arasindaki fark: arange'de artis miktarini belirtiyoruz, linspace'de ise kac sayi olusturacagimizi belirtiyoruz

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 2.  4.  6.  8. 10.]


In [51]:
print(np.logspace(1, 3, 5)) # 10^1 ile 10^3 arasinda esit araliklarla 5 sayi olusturur, 10^3 dahil
print(np.logspace(0, 2, 5, dtype = int)) # 10^0 ile 10^2 arasinda esit araliklarla 5 sayi olusturur, 10^2 dahil, sayilari integer yapar

[  10.           31.6227766   100.          316.22776602 1000.        ]
[  1   3  10  31 100]


In [53]:
print(np.zeros(5)) # 5 tane 0'dan olusan array olusturur
print(np.zeros((3, 3))) # 3 satir 3 sutunluk 0'lardan olusan array olusturur
print(np.ones((3, 5))) # 3 satir 5 sutunluk 1'lerden olusan array olusturur
print(np.full((3, 4), 9)) # 3 satir 4 sutunluk 9'lardan olusan array olusturur
print(np.eye(5)) # 5x5'lik birim matris olusturur

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [50]:
np.zeros((2,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [57]:
np.linspace(0, 1000, 26, dtype = int)

array([   0,   40,   80,  120,  160,  200,  240,  280,  320,  360,  400,
        440,  480,  520,  560,  600,  640,  680,  720,  760,  800,  840,
        880,  920,  960, 1000])

In [58]:
np.random.rand(3) # 0 ile 1 arasinda 3 tane random sayi olusturur

array([0.14424031, 0.47117072, 0.81503074])

In [59]:
np.random.rand(3, 4) # 0 ile 1 arasinda 3 satir 4 sutunluk random sayilarla dolu array olusturur

array([[0.53146197, 0.06761239, 0.81229897, 0.0527118 ],
       [0.7012193 , 0.35534464, 0.45933818, 0.26703035],
       [0.91065889, 0.54157609, 0.77673042, 0.56546893]])

In [60]:
np.random.rand(3) * 10 # 0 ile 10 arasinda 3 tane random sayi olusturur

array([5.83198835, 2.12995071, 1.88289832])

In [62]:
np.random.randint(0, 100, 5) # 0 ile 100 arasinda 5 tane random tam sayi olusturur, 100 dahil degil

array([34, 92, 20,  4, 67], dtype=int32)

In [63]:
np.random.randint(15, 100, (3, 2)) # 15 ile 100 arasinda 3 satir 2 sutun random tam sayi olusturur, 100 dahil degil

array([[45, 44],
       [88, 55],
       [57, 24]], dtype=int32)

In [64]:
np.random.randint(0, 50, (4, 6))

array([[ 4, 15, 34, 46, 44, 15],
       [49, 39, 20, 15,  5, 13],
       [ 4, 32, 29, 15, 35, 13],
       [44, 29, 48, 18, 35,  2]], dtype=int32)