# NumPy Egzersizleri

1. NumPy kütüphanesi np kısaltması ile import edin

In [3]:
import numpy as np

2. 10 tane 0 değerinden oluşan bir array oluşturun

In [5]:
soru2 = np.zeros(10)
soru2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. 10 tane 1 değerinden oluşan bir array oluşturun

In [7]:
soru3 = np.ones(10)
soru3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. 10 tane 5 değerinden oluşan bir array oluşturun

In [8]:
soru4 = np.ones(10) * 5
soru4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. 10'dan 50'ye kadar(10 ve 50 dahil) ardışık tam sayılardan oluşan bir array oluşturalım

In [9]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. 10 ve 50 arasındaki çift tam sayılardan oluşan bir array oluşturalım. (10 ve 50 dahil)

In [10]:
np.arange(10 ,51 ,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. 3x3 shape'inde 0'dan 8'e kadar toplam 9 tam sayıdan oluşan bir array oluşturalım

In [11]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. 3x3 boyutlarında birim matris oluşturun

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. NumPy kullanarak 0-1 arasından rastgele bir sayı oluşturun.

 NOT: Değerler random seçildiği için sizin sonucunuz aşağıdaki çıktıdan farklı olacaktır

In [13]:
np.random.rand()

0.3170229667152641

10. NumPy kullanarak standart dağılıma sahip 25 random sayıdan oluşan bir array oluşturalım.

  NOT: Sizin cevabınız aşağıdaki çıktıdan farklı olacaktır

In [14]:
np.random.randn(25)

array([-0.08967818, -0.32384211, -0.67106516,  0.70626628,  0.8142416 ,
        1.42472435, -1.80634854,  0.76582895,  0.63609741, -0.60468111,
       -0.14255076, -1.03920898, -0.32412872,  0.82082067, -0.63407505,
       -0.29061263, -0.54590779,  1.00497046,  1.09070308,  0.49527491,
        0.10627624,  0.99199002,  0.98453642,  0.62796783,  0.02847465])

11. Aşağıdaki çıktıdakine benzer array'i oluşturmaya çalışın

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [15]:
np.arange(0.01, 1.01, 0.01).reshape(10, -1)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. 0-1 arasında lineer artış gösteren ve 20 sayıdan oluşan bir array oluşturun:

In [16]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# NumPy Indexleme ve Secme

Aşağıdaki matris sıradaki sorular için bizim başlangıç matrisimiz. (Aşağıdaki kod hücresini çalıştırarak devam edin.), devamında sorduğumuz soruları cevaplamaya çalışın:

In [17]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

13. Aşağıda verilen matrisleri oluşturmaya çalışın.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

14. Parantez içinde gösterilen çıktıyı üreten kodu yazın. (20)

In [21]:
mat[3][4]

np.int64(20)

15. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

array([[ 2],
       [ 7],
       [12]])

In [22]:
mat[0: 3, 1: 2]

array([[ 2],
       [ 7],
       [12]])

16. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

array([21, 22, 23, 24, 25])

In [26]:
mat[4]

array([21, 22, 23, 24, 25])

17. mat arrayini kullanarak aşağıdaki matris çıktısını verecek kodları oluşturun

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[3: 5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# NumPy Operasyonlari

18. Mat arrayindeki bütün değerlerin toplamını bulun

In [27]:
mat.sum()

np.int64(325)

19. Mat arrayindeki değerlerin standart sapmasını bulun

In [28]:
mat.std()

np.float64(7.211102550927978)

20. Mat arrayindeki her sütunun kendi içinde toplamlarını bularak yeni bir array oluşturun

In [44]:
mat1 = np.sum(mat, axis = 1) # np.sum() : satırları toplamak için axis=1, sütunları toplamak için axis=0 kullanılır.
mat1

array([ 15,  40,  65,  90, 115])

# Tebrikler, NumPy temelleri öğrenilmiş!