In [13]:
import numpy as np

In [14]:
arr1d = np.arange(10)

In [15]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1d.ndim # ndim = kac boyutlu oldugunu gosterir

1

In [17]:
arr2d = np.zeros((3,5))

In [18]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
arr2d.ndim

2

In [20]:
arr2d.shape # shape = satir ve sutun sayilarini gosterir

(3, 5)

In [21]:
arr3d = np.zeros((2,3,4)) # 2 tane 3 satir 4 sutun olan matris

In [22]:
arr3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
arr3d.ndim

3

In [24]:
arr3d.shape # 2 tane 3 satir 4 sutun olan matris

(2, 3, 4)

In [25]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1d[3] # indexleme

np.int64(3)

In [39]:
arr2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2d[0] # 0. satir

array([0., 0., 0., 0., 0.])

In [ ]:
arr2d[2][0] # 2. satirin 0. sutunu

np.float64(0.0)

In [42]:
arr3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3d[1][2][0] # 1. matrisin 2. satirinin 0. sutunu

np.float64(0.0)

In [45]:
np.arange(53, 62)[4]

np.int64(57)

In [ ]:
arr = np.random.randint(0, 100, 10) # 0-100 arasinda 10 tane rastgele sayi
arr

array([76, 50, 28, 81,  7, 66,  2, 35, 54, 85], dtype=int32)

In [ ]:
arr.max() # max degeri verir

np.int32(85)

In [ ]:
arr.argmax() # max degerin indexini verir

np.int64(9)

In [49]:
arr.min() # min degeri verir

np.int32(2)

In [50]:
arr.argmin() # min degerin indexini verir

np.int64(6)

In [ ]:
print(arr[5:]) # slicing, 5. indexten sona kadar
print(arr[5:7]) # slicing, 5. indexten 7. indexe kadar
print(arr[2:10:2]) # slicing, 2. indexten 9. indexe kadar 2ser 2ser al
print(arr[::-1]) # slicing, ters cevirme
arr[5:7] = 55 # 5. ve 6. indexteki degeri 55 yap
print(arr)

[55 55 35 54 85]
[55 55]
[28  7 55 54]
[85 54 35 55 55  7 81 28 50 76]
[76 50 28 81  7 55 55 35 54 85]


In [62]:
np.arange(-30, 11)[5:19] # -30 ile 10 arasindaki sayilarin 5. indexinden 18. indexine kadar

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

In [67]:
arr.dtype # dtype = data type, veri tipini gosterir

dtype('int32')

In [76]:
arr2 = np.arange(0, 50, 4, dtype = float) # 0-50 arasinda float tipinde sayilar
arr2

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.])

In [ ]:
arr2.dtype

dtype('float64')

In [78]:
arr3 = np.array(["a", "b", "c"])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [79]:
arr3.dtype

dtype('<U1')

In [81]:
arr4 = np.array([1.2, 3.8, 5.2])
arr4

array([1.2, 3.8, 5.2])

In [82]:
arr4.dtype

dtype('float64')

In [85]:
arr4.astype(int) # float tipindeki sayilari int tipine cevirir, degerlerden kayiplar olur

array([1, 3, 5])

In [86]:
arr5 = np.array(["5", "7", "19", "1", "22", "99", "4"])
arr5

array(['5', '7', '19', '1', '22', '99', '4'], dtype='<U2')

In [87]:
arr5.dtype

dtype('<U2')

In [88]:
arr5.astype(int) # string tipindeki sayilari int tipine cevirir

array([ 5,  7, 19,  1, 22, 99,  4])