In [3]:
import numpy as np

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10).reshape(2, 5) # reshape arrayin seklini degistirir
# np.arange(10).reshape(2, 3) -> hata verir cunku 2*3=6 oldugundan 10'a esit degil 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

***arange ile array oluştururken tek boyutlu oldugundan reshape bu konuda cok kullanisli oluyor***

In [10]:
print(np.ones(12), "\n")
print(np.ones(12).reshape(3, 4))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


***Bilinmeyen Boyut !***

reshape methodu kullanilirken hesaplamak istedigimiz boyut yerine -1 yazip otomatik hesaplatabiliriz.

In [20]:
np.arange(120).reshape(5, -1, 8) # -1 yazinca numpy otomatik hesapliyor

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119]]])

In [29]:
arr1 = np.arange(60)
arr1 = arr1.reshape(3, 2, -1) # 3 tane 2 satir 10 sutun arraye donusturur

In [31]:
arr2d = np.arange(1, 13).reshape(3, 4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr2d.reshape(-1) # (flatten) tek boyutlu hale getirir 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
arr3d = np.arange(12).reshape(2, 3, 2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [47]:
print(arr3d.shape)
print(arr3d.ndim, "\n")
print(arr3d.reshape(3, -1), "\n") # 3 boyutlu arrayi 2 boyutluya cevirir
print(arr3d.reshape(-1)) # 3 boyutlu arrayi tek boyutlu hale getirir


(2, 3, 2)
3 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [51]:
arr1d = np.arange(1, 13)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
for i in arr1d:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [53]:
arr2d = np.arange(1, 13).reshape(3, 4)
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
for i in arr2d:
    print(i) #satirlari birer eleman olarak alir

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [ ]:
for i in arr2d:
    for j in i:
        print(j)
# her bir elemani tek tek yazdirir, satir satir degil
# karmasik yapilar icin kullanilabilir
# verimli degil

1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [59]:
for i in arr3d:
    for j in i:
        for k in j:
            print(k)
# 3 boyutlu arraydeki her bir elemani tek tek yazdirir
# performans olarak cok verimli degil ancak karmasik yapilar icin kullanilabilir
# zaman acisindan maliyetli olabilir
# genellikle ic ice for yazmaktan kacinilir
# arrayin boyutu kac ise o kadar for kullanilarak o arrayin butun elemanlarina erisilir

0
1
2
3
4
5
6
7
8
9
10
11


***cok boyutlu arraylerde nditer() kullanilir***

***for dongusune gore cok daha efektif ve hizli bir sekilde tum elemanlari donmeyi saglar***


In [60]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [62]:
np.nditer(arr3d) # bunun veri tipi nditer objesidir, for dongusu ile icindeki elemanlar gezilebilir

In [70]:
for i in np.nditer(arr3d): # 1 for ile 3 boyutlu arraydeki tum elemanlara erisilir
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
